/**
 * Standalone demo telemetry dataset for static hosting (GitHub Pages)
 * Ensures the app works 100% interactively without requiring a local Python server.
 */

export const mockSummary = {
  user: "Aarav Sharma",
  total_spend: 124560,
  this_month: 41540,
  last_month: 38200,
  month_change_pct: 15.2,
  transactions: 269,
  transactions_this_month: 84,
  open_anomalies: 33,
  open_by_severity: { High: 18, Medium: 12, Low: 3 },
  amount_at_risk: 74200,
  by_category: [
    { category: "Bills", total: 32000 },
    { category: "Shopping", total: 24500 },
    { category: "Food", total: 14200 },
    { category: "Travel", total: 9800 },
    { category: "Entertainment", total: 4200 },
    { category: "Health", total: 3500 },
  ],
  by_category_month: [
    { category: "Bills", total: 25000 },
    { category: "Shopping", total: 8400 },
    { category: "Food", total: 5200 },
  ],
  daily: [
    { date: "2026-09-24", label: "24 Sep", total: 1450, count: 4, anomalous: false, risk: 0 },
    { date: "2026-09-25", label: "25 Sep", total: 2890, count: 5, anomalous: false, risk: 0 },
    { date: "2026-09-26", label: "26 Sep", total: 18750, count: 2, anomalous: true, risk: 78 },
    { date: "2026-09-27", label: "27 Sep", total: 3200, count: 4, anomalous: false, risk: 0 },
    { date: "2026-09-28", label: "28 Sep", total: 2349, count: 3, anomalous: true, risk: 65 },
    { date: "2026-09-29", label: "29 Sep", total: 850, count: 2, anomalous: false, risk: 0 },
    { date: "2026-09-30", label: "30 Sep", total: 42999, count: 3, anomalous: true, risk: 92 },
    { date: "2026-10-01", label: "01 Oct", total: 26400, count: 6, anomalous: false, risk: 0 },
    { date: "2026-10-02", label: "02 Oct", total: 3400, count: 5, anomalous: false, risk: 0 },
    { date: "2026-10-03", label: "03 Oct", total: 1240, count: 3, anomalous: true, risk: 42 },
    { date: "2026-10-04", label: "04 Oct", total: 5400, count: 4, anomalous: false, risk: 0 },
    { date: "2026-10-05", label: "05 Oct", total: 10000, count: 2, anomalous: true, risk: 74 },
    { date: "2026-10-06", label: "06 Oct", total: 2100, count: 3, anomalous: false, risk: 0 },
    { date: "2026-10-07", label: "07 Oct", total: 3450, count: 4, anomalous: false, risk: 0 },
  ],
  weekday: [
    { day: "Mon", count: 28 },
    { day: "Tue", count: 34 },
    { day: "Wed", count: 52 },
    { day: "Thu", count: 40 },
    { day: "Fri", count: 46 },
    { day: "Sat", count: 54 },
    { day: "Sun", count: 35 },
  ],
  hourly: Array.from({ length: 24 }).map((_, h) => ({ hour: h, count: h > 8 && h < 23 ? 12 + (h % 5) : 2 })),
  budgets: [
    { category: "Bills", monthly_limit: 32000, actual: 26858, pct: 83.9, over: false },
    { category: "Food", monthly_limit: 14000, actual: 11450, pct: 81.8, over: false },
    { category: "Shopping", monthly_limit: 9000, actual: 12400, pct: 137.8, over: true },
    { category: "Travel", monthly_limit: 6000, actual: 4850, pct: 80.8, over: false },
    { category: "Entertainment", monthly_limit: 3000, actual: 2840, pct: 94.7, over: false },
  ],
  immunity: {
    score: 75,
    label: "Strong",
    components: { resolution: 32.5, learning: 24.0, budget: 18.5 },
    resolved: 14,
    open: 19,
    antibodies: 4,
    whitelist: 2,
  },
  impulse: { avoided: 8240, cancelled: 3, proceeded: 2 },
  learning: [
    {
      kind: "fraud",
      open_before: 20,
      open_after: 19,
      immunity_before: 71,
      immunity_after: 75,
      note: "Antibody #4 now guards against 3 AM electronics purchases.",
      created_at: new Date().toISOString(),
    },
  ],
  antibody_hits: 4,
};

export const mockAnomalies = [
  {
    id: 1,
    expense_id: 101,
    risk_score: 92,
    severity: "High",
    reasons: [
      "Robust z-score 8.4 > 3.5: ₹42,999 is 14.3× your typical Shopping median (₹3,000).",
      "IsolationForest ML anomaly: rare transaction vector and high magnitude deviation.",
    ],
    contributions: [
      { detector: "robust_z", label: "Amount Outlier", score: 40.0, reason: "14.3× typical shopping median" },
      { detector: "isolation_forest", label: "ML Isolation", score: 20.0, reason: "Anomalous multi-feature vector" },
      { detector: "first_time_merchant", label: "New Merchant", score: 22.0, reason: "First time luxury purchase" },
      { detector: "round_number", label: "Round Amount", score: 10.0, reason: "High value round payment" },
    ],
    counterfactuals: [
      "Would not be flagged if the amount were ≤ ₹4,200 (instead of ₹42,999).",
      "Would carry less risk if made at a merchant you've paid multiple times before.",
    ],
    status: "open",
    blocked_by_antibody_id: null,
    created_at: new Date().toISOString(),
    expense: {
      id: 101,
      date: "2026-09-30",
      time: "15:12",
      merchant: "Amazon Electronics High-Value",
      amount: 42999,
      category: "Shopping",
      payment_method: "Credit Card",
      location: "Online",
    },
  },
  {
    id: 2,
    expense_id: 102,
    risk_score: 85,
    severity: "High",
    reasons: [
      "Impossible travel: Bengaluru → Delhi (1,740 km) in 45 min would require 2,320 km/h (speed limit 800 km/h).",
    ],
    contributions: [
      { detector: "impossible_travel", label: "Impossible Travel", score: 35.0, reason: "1,740 km in 45 min" },
      { detector: "first_time_merchant", label: "New Merchant", score: 22.0, reason: "New Delhi duty free store" },
      { detector: "robust_z", label: "Amount Outlier", score: 28.0, reason: "High shopping expenditure" },
    ],
    counterfactuals: [
      "Would not be flagged if this purchase had happened in Bengaluru (your last known city).",
    ],
    status: "open",
    blocked_by_antibody_id: null,
    created_at: new Date().toISOString(),
    expense: {
      id: 102,
      date: "2026-10-02",
      time: "13:50",
      merchant: "Delhi Duty Free Electronics",
      amount: 16450,
      category: "Shopping",
      payment_method: "Credit Card",
      location: "Delhi",
    },
  },
  {
    id: 3,
    expense_id: 103,
    risk_score: 72,
    severity: "High",
    reasons: [
      "Possible duplicate: Myntra charged the identical amount ₹2,349 within 2.0 hours (prior txn #89).",
    ],
    contributions: [
      { detector: "duplicate", label: "Duplicate Charge", score: 30.0, reason: "Identical ₹2,349 in 2 hours" },
      { detector: "burst", label: "Shopping Burst", score: 22.0, reason: "Repeated shopping checkouts" },
    ],
    counterfactuals: [
      "Would not be flagged if this were the only charge from Myntra within 48 hours.",
    ],
    status: "open",
    blocked_by_antibody_id: null,
    created_at: new Date().toISOString(),
    expense: {
      id: 103,
      date: "2026-09-28",
      time: "14:22",
      merchant: "Myntra",
      amount: 2349,
      category: "Shopping",
      payment_method: "Credit Card",
      location: "Online",
    },
  },
  {
    id: 4,
    expense_id: 104,
    risk_score: 68,
    severity: "High",
    reasons: [
      "Purchased at 03:52 AM: only 1.8% of your transactions happen between midnight and 5 AM.",
    ],
    contributions: [
      { detector: "late_night", label: "Late-Night Purchase", score: 18.0, reason: "3:52 AM off-peak transaction" },
      { detector: "robust_z", label: "Food Outlier", score: 25.0, reason: "3.2× regular Swiggy Instamart order" },
    ],
    counterfactuals: [
      "Would not be flagged if made during normal waking hours (between 8 AM and 10 PM).",
    ],
    status: "open",
    blocked_by_antibody_id: null,
    created_at: new Date().toISOString(),
    expense: {
      id: 104,
      date: "2026-10-03",
      time: "03:52",
      merchant: "Swiggy Instamart",
      amount: 1240,
      category: "Food",
      payment_method: "UPI",
      location: "Bengaluru",
    },
  },
  {
    id: 5,
    expense_id: 105,
    risk_score: 64,
    severity: "High",
    reasons: [
      "Burst anomaly: 6 Shopping transactions recorded within a 4-hour window.",
    ],
    contributions: [
      { detector: "burst", label: "Spending Burst", score: 28.0, reason: "6 shopping checkouts in one afternoon" },
      { detector: "isolation_forest", label: "Velocity Outlier", score: 16.0, reason: "Rapid cadence anomaly" },
    ],
    counterfactuals: [
      "Would not be flagged with fewer than 5 Shopping purchases in a single day.",
    ],
    status: "open",
    blocked_by_antibody_id: null,
    created_at: new Date().toISOString(),
    expense: {
      id: 105,
      date: "2026-09-25",
      time: "16:15",
      merchant: "Ajio Trends",
      amount: 1799,
      category: "Shopping",
      payment_method: "Credit Card",
      location: "Online",
    },
  },
];

export const mockExpenses = [
  ...mockAnomalies.map((a) => a.expense),
  { id: 1, date: "2026-10-07", time: "11:20", merchant: "Swiggy", amount: 340, category: "Food", payment_method: "UPI", location: "Bengaluru", notes: "Lunch order" },
  { id: 2, date: "2026-10-07", time: "09:15", merchant: "Uber", amount: 280, category: "Travel", payment_method: "UPI", location: "Bengaluru", notes: "Cab to office" },
  { id: 3, date: "2026-10-06", time: "20:45", merchant: "Starbucks", amount: 480, category: "Food", payment_method: "Credit Card", location: "Bengaluru", notes: "Coffee" },
  { id: 4, date: "2026-10-06", time: "18:30", merchant: "Amazon", amount: 1299, category: "Shopping", payment_method: "Credit Card", location: "Online", notes: "Books & cables" },
  { id: 5, date: "2026-10-05", time: "10:00", merchant: "ACT Fibernet", amount: 1059, category: "Bills", payment_method: "UPI", location: "Bengaluru", notes: "Monthly broadband" },
  { id: 6, date: "2026-10-04", time: "19:00", merchant: "Cult.fit Membership", amount: 1499, category: "Health", payment_method: "Credit Card", location: "Online", notes: "Gym renewal" },
  { id: 7, date: "2026-10-03", time: "21:10", merchant: "Netflix", amount: 649, category: "Entertainment", payment_method: "Credit Card", location: "Online", notes: "OTT Subscription" },
  { id: 8, date: "2026-10-02", time: "08:30", merchant: "BESCOM Electricity", amount: 1750, category: "Bills", payment_method: "Net Banking", location: "Bengaluru", notes: "Electricity bill" },
  { id: 9, date: "2026-10-01", time: "09:05", merchant: "NoBroker Rent", amount: 25000, category: "Bills", payment_method: "Net Banking", location: "Bengaluru", notes: "October rent" },
];

export const mockTimeline = [
  { date: "2026-09-01", label: "01 Sep", spend: 28000, cumulative: 28000, flags: 0, flagged_total: 0, resolved_total: 0, antibodies: 0, temperature: 36.5, immunity: 70 },
  { date: "2026-09-10", label: "10 Sep", spend: 3200, cumulative: 52000, flags: 1, flagged_total: 2, resolved_total: 1, antibodies: 1, temperature: 36.7, immunity: 72 },
  { date: "2026-09-20", label: "20 Sep", spend: 4100, cumulative: 81000, flags: 2, flagged_total: 5, resolved_total: 4, antibodies: 2, temperature: 37.1, immunity: 73 },
  { date: "2026-09-30", label: "30 Sep", spend: 43000, cumulative: 108000, flags: 3, flagged_total: 9, resolved_total: 7, antibodies: 3, temperature: 38.2, immunity: 74 },
  { date: "2026-10-07", label: "07 Oct", spend: 3450, cumulative: 124560, flags: 1, flagged_total: 33, resolved_total: 14, antibodies: 4, temperature: 36.8, immunity: 75 },
];
